name: Build and Deploy Swagger Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install swagger-cli
        run: npm install -g swagger-cli swagger-ui-dist
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
            output: swagger-ui
            spec-file: swagger-tutorial.yaml
      - name: Upload document
        uses: actions/upload-pages-artifact@v3
        with:
          path: swagger-ui

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deployment-pages@v4
